server:
  port: 8888
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/

spring:
  application:
    name: siwei-config-server

# 配置通过git获取配置信息
#  cloud:
#    siwei-config:
#      server:
#        git:
#          uri: http://47.99.73.235:3000/siwei/siwei-config.git
##          search-paths: '{profile}' # git仓库地址下的相对地址，可以配置多个，用,分割。
#          search-paths: siwei-config # git仓库地址下的相对地址，可以配置多个，用,分割。
#          username: ******
#          password: ******
#      label: master

#设置为本地启动的方式，而不是通过git
  profiles:
    active: native #设置为本地启动的方式，而不是通过git
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/siwei-config

#cloud bus rabbitmq
    bus:
      enabled: true
      trace:
        enabled: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
management:
  endpoints:
    web:
      exposure:
        include: "*"
